Support for -gdwarf-5 option in Flang driver.
flang-compiler/flang-driver pull request #89
Opened 2020-02-06 09:46 UTC by alokkrsharma

Summary:
  FLANG driver doesnt pass -gdwarf-4/5 to flang1 in form of xbits,
while it passes for -gdwarf-2/3
   -gdwarf-2 => -x 120 0x200
   -gdwarf-3 => -x 120 0x4000

Due to this -gdwarf-5 is never honored and default option -gdwarf-4
is taken.
    # flang -gdwarf-5 test.f90
    # llvm-dwarfdump a.out | grep version
    0x00000000: Compile Unit: length = 0x0000008e version = 0x0004

  Now 0x1000000/0x2000000 will be passed for -gdwarf-4/5
   -gdwarf-4 => -x 120 0x1000000
   -gdwarf-5 => -x 120 0x2000000

Testing:
  - GNU gdb fortran testsuite
  - check-llvm
  - check-debuginfo

Change-Id: I3d8fa0c4bd554787a6ac0fd3aca7d73ce7d9c9f1

2020-02-06 17:25 UTC, schweitzpgi commented
Are these new bit flags? Have they already been added to the flang1/flang2 code?

2020-02-06 17:30 UTC, alokkrsharma commented
> 
> 
> Are these new bit flags? Have they already been added to the flang1/flang2 code?

Thanks a lot for your time on this.
That is under review as https://github.com/flang-compiler/flang/pull/863

Regards,
Alok

2020-02-06 17:37 UTC, schweitzpgi approved these changes
This looks great. Thanks for implementing this feature.

2020-02-07 06:13 UTC, alokkrsharma commented
> 
> 
> This looks great. Thanks for implementing this feature.

Thanks a lot for approving this. I am sorry as I would be bothering you with some queries.
- As I don't have write access, if it is ready to be merged, would you please do that on my behalf?
- Current target for merge is 'master', do i need to raise separate pull request for other branches such as release_60/release_70 etc or that would happen automatically ?
Thanks in advance !!

2020-04-13 06:08 UTC, alokkrsharma commented
Hi gklimowicz , do you have any more comments on this?

2020-04-14 16:09 UTC, gklimowicz commented
@jiel-nv Can you take a look at this one, too, please? I am taking myself off the reviewer list. Given that @schweitzpgi is happy, odds are you will be as well. Then I will plan to merge it in.

2020-04-14 21:24 UTC, jiel-nv approved these changes

2020-09-11 23:01 UTC, gklimowicz requested changes
This pull request is against the `master` branch of flang-driver. We don't really do any work on master except when pull changes forward from the llvm-mirror. This PR, along with PR#90 and PR#91 seem to have conflicts when attempting to merge against release_90.

It seems like #89, #90 and #91 should be replaced with a single pull request that addresses all the changes, against release_90 (and possibly release_80, if it is not difficult), and does not have merge conflicts.

2020-09-12 11:53 UTC, alokkrsharma commented
> 
> 
> This pull request is against the `master` branch of flang-driver. We don't really do any work on master except when pull changes forward from the llvm-mirror. This PR, along with PR#90 and PR#91 seem to have conflicts when attempting to merge against release_90.
> 
> It seems like #89, #90 and #91 should be replaced with a single pull request that addresses all the changes, against release_90 (and possibly release_80, if it is not difficult), and does not have merge conflicts.

#92 is up which is merge of #89 #90 and #91 on top of release_90. Please let me know it this is what you expect. I shall raise another one for release_80.

2020-10-08 15:12 UTC, closed without merging

2020-10-08 15:13 UTC, alokkrsharma commented
This is merged as part of #92 and #93 .